// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_8_FONT_ID (-2022789252)
#else
#define LEXENDDECA_8_FONT_ID (-2044145940)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_9_FONT_ID (-1206441199)
#else
#define LEXENDDECA_9_FONT_ID (2003672599)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_10_FONT_ID (848942201)
#else
#define LEXENDDECA_10_FONT_ID (1144677629)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_12_FONT_ID (998273723)
#else
#define LEXENDDECA_12_FONT_ID (1926983473)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_14_FONT_ID (-1351448868)
#else
#define LEXENDDECA_14_FONT_ID (-1406445118)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_16_FONT_ID (-1656483080)
#else
#define LEXENDDECA_16_FONT_ID (2019090238)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_18_FONT_ID (-1005241028)
#else
#define LEXENDDECA_18_FONT_ID (1302402945)
#endif
#ifdef OMIT_EMOJI_FONTS
#define LEXENDDECA_20_FONT_ID (-1863552944)
#else
#define LEXENDDECA_20_FONT_ID (-1459152267)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_8_FONT_ID (-2130262487)
#else
#define CHAREINK_8_FONT_ID (312370057)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_9_FONT_ID (-1667541806)
#else
#define CHAREINK_9_FONT_ID (631165824)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_10_FONT_ID (1310190783)
#else
#define CHAREINK_10_FONT_ID (-944299713)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_12_FONT_ID (865209132)
#else
#define CHAREINK_12_FONT_ID (562864807)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_14_FONT_ID (892739170)
#else
#define CHAREINK_14_FONT_ID (-1176545950)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_16_FONT_ID (1747724046)
#else
#define CHAREINK_16_FONT_ID (-1477679466)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_18_FONT_ID (438073136)
#else
#define CHAREINK_18_FONT_ID (-787708407)
#endif
#ifdef OMIT_EMOJI_FONTS
#define CHAREINK_20_FONT_ID (1321537766)
#else
#define CHAREINK_20_FONT_ID (-390579825)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_8_FONT_ID (1494210917)
#else
#define BITTER_8_FONT_ID (1806590679)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_9_FONT_ID (-1567154940)
#else
#define BITTER_9_FONT_ID (1731841716)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_10_FONT_ID (-1829239971)
#else
#define BITTER_10_FONT_ID (-1242223189)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_12_FONT_ID (1963441729)
#else
#define BITTER_12_FONT_ID (611815583)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_14_FONT_ID (-1705318616)
#else
#define BITTER_14_FONT_ID (167846617)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_16_FONT_ID (1467653849)
#else
#define BITTER_16_FONT_ID (-1284751464)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_18_FONT_ID (-582927980)
#else
#define BITTER_18_FONT_ID (-1308817601)
#endif
#ifdef OMIT_EMOJI_FONTS
#define BITTER_20_FONT_ID (-2104090569)
#else
#define BITTER_20_FONT_ID (1392022129)
#endif
#define UI_10_FONT_ID (-227549249)
#define UI_12_FONT_ID (652043988)
#define SMALL_FONT_ID (-1760306835)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LEXENDDECA_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
